// option/option.ts

import Some from "./some.ts";
import None from "./none.ts";

/**
 * Represents a value that may be present (`Some`) or absent (`None`).
 *
 * @template T Type of the value.
 */
export abstract class Option<T> {
  /**
   * Creates an `Option` from a "nullable" value, returns `None` if `null`/`undefined`, `Some` otherwise.
   *
   * @template T Type of the value.
   * @returns `Some` with the value or `None` if nullable.
   */
  public static from<T>(value: T): Option<NonNullable<T>> {
    return value == null ? None : Some(value);
  }

  /**
   * Checks if it has a value.
   *
   * @returns `true` if it contains a value, `false` otherwise.
   */
  public abstract isSome(): this is Option<NonNullable<T>>;

  /**
   * Checks if it is empty.
   *
   * @returns `true` if it is empty, `false` otherwise.
   */
  public abstract isNone(): this is Option<never>;

  /**
   * Applies `fn` to the value (if `Some`), and returns a new `Some` containing the result.
   *
   * @param fn - Function to apply to the contained value.
   * @returns A new Option of type Some containing the result of the function.
   */
  public abstract map<U>(fn: (value: NonNullable<T>) => U): Option<NonNullable<U>>;

  /**
   * Matches the type of the Option and executes the apropriate *handler* function.
   *
   * @param handlers - Object containing functions to be called on each variant of `Option`.
   * @returns Any value generated by the executed handler.
   */
  public abstract match<U>({ Some, None }: { Some: (value: NonNullable<T>) => U; None: () => U }): U;

  /**
   * Returns the contained value or the provided *default* if it is empty.
   *
   * @param defaultValue - Value to be used in case of None.
   * @returns The contained success value or the default.
   */
  public abstract or(defaultValue: NonNullable<T>): NonNullable<T>;

  /**
   * Returns the contained value or throws an exception if `None`.
   *
   * @returns The contained value.
   */
  public abstract unwrap(): NonNullable<T> | never;
}

export { None, Some };
